# Dockerfile
FROM python:3.11-slim AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Second stage: Create the final image
#-------------------------------------------------------------------
FROM python:3.11-slim

# Set environment variables to prevent Python from writing .pyc files and to ensure output is sent straight away to the terminal without buffering  

# What is .pyc file?
#* .pyc files are compiled Python files that are generated by the Python interpreter to improve the performance of Python programs. When a Python script is executed, the interpreter compiles the source code into bytecode, which is a lower-level representation of the code that can be executed more efficiently. The resulting bytecode is stored in .pyc files, which are created in the same directory as the original .py files. These .pyc files can be reused in subsequent runs of the program, allowing for faster execution since the interpreter can skip the compilation step if the .pyc file is up to date with the corresponding .py file. However, in some cases, such as when developing or debugging, it may be desirable to prevent the creation of .pyc files, which is why the PYTHONDONTWRITEBYTECODE environment variable is set to 1 in this Dockerfile.
ENV PYTHONDONTWRITEBYTECODE=1 \
	PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY main.py index.html best_diabetes_model.pkl ./

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
