apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: kserve-xgbserver
spec:
  supportedModelFormats:
    - name: xgboost
      version: "1"
      autoSelect: true
  containers:
    - name: kserve-container
      image: kserve/xgbserver:v0.11.0
      args:
        - --model_name=diabetes-xgboost
        - --model_dir=/mnt/models
      ports:
        - containerPort: 8080
          name: http1
---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: diabetes-xgboost
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
    argocd.argoproj.io/sync-wave: "1"  # runs after job completes
spec:
  predictor:
    minReplicas: 1
    maxReplicas: 5
    model:
      modelFormat:
        name: xgboost
        version: "1"
      storageUri: pvc://diabetes-model-pvc/diabetes/v1
  canaryTrafficPercent: 20
  canaryPredictor:
    minReplicas: 1
    maxReplicas: 2
    model:
      modelFormat:
        name: xgboost
        version: "1"
      storageUri: pvc://diabetes-model-pvc/diabetes/v2