name: mlops-pipeline

"on":
  push:
    branches:
      - feat/kserve
    paths:
      - 'Dockerfile'
      - '.github/workflows/dockerhub-publish.yml'
      - 'requirements.txt'
      - 'main.py'
      - 'tests/test_artifact.py'
      - 'index.html'

permissions:
  contents: write

env:
  IMAGE_NAME: shalindra936/diabetes-prediction-model
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run artifact tests
        run: |
          set -euo pipefail
          mkdir -p reports
          pytest -q \
            --junitxml=reports/pytest.xml \
            --html=reports/pytest.html \
            --self-contained-html \
            2>&1 | tee reports/pytest.txt

      - name: Email test report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "MLOps Test Report for Diabetes Prediction Model - Run #${{ github.run_number }}"
          to: ${{ secrets.SMTP_USERNAME }}
          from: ${{ secrets.SMTP_USERNAME }}
          body: "Test run for MLops Pipeline for${{ github.sha }} completed with status: ${{ job.status }}. See attached reports."
          attachments: reports/pytest.txt, reports/pytest.xml, reports/pytest.html

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


# Updating the image tag in the manifest files and committing the changes back to the repository
      - name: Update k8s image tag
        run: |
          set -euo pipefail
          sed -i "s|image: .*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" KServe/fastapi-deployment.yaml


      - name: Commit k8s image tag
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add KServe/fastapi-deployment.yaml
          git commit -m "chore: update k8s image tag to ${IMAGE_TAG}"
          git push
